/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    RecordSpine: typeof import('./src/components/RecordSpine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SleevePanel: typeof import('./src/components/SleevePanel.vue')['default']
    SourceIcon: typeof import('./src/components/SourceIcon.vue')['default']
    StationBar: typeof import('./src/components/StationBar.vue')['default']
    SyncRibbon: typeof import('./src/components/SyncRibbon.vue')['default']
  }
}
