/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    PlaylistCard: typeof import('./src/components/PlaylistCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SleevePanel: typeof import('./src/components/SleevePanel.vue')['default']
    SourceIcon: typeof import('./src/components/SourceIcon.vue')['default']
    StationBar: typeof import('./src/components/StationBar.vue')['default']
  }
}
